messages:
    colors:
        primary: "&#ffd4e3"
        secondary: "&#ffb5cf"
        error: "&#ff6e6e"

    must-be-player: Console cannot execute this command.
    no-permission: You don't have permission to execute this command.
    player-is-offline: That player is offline.
