name: TarnaIsBad
version: '${project.version}'
main: me.aroze.tarnaisbad.TarnaIsBad
api-version: 1.19
authors: [ Aroze, Goose ]
description: tarns sucks. tarna bad. tarna poopy. tarna dookie.
website: https://github.com/UwUAroze/TarnaIsBad
commands:
  deletehome:
    description: Delete a home.
    aliases: [ delhome ]

  homes:
    description: View your homes.

  home:
    description: Go to a home.

  sethome:
    description: Set a home.

  deletewarp:
    description: Delete a warp.
    aliases: [ delwarp ]

  setwarp:
    description: Set a warp.

  warp:
    description: Go to a warp.

  warps:
    description: View all warps.

  migrate:
    description: Migrate homes and warps from Skript variables.
    permission: tarnaisbad.migrate